### ISSUE TITLE
Other US open data scrapers

### ISSUE THREAD

**Issue by hugovk** [edsu/opinions#1]
This application and the resulting data might be something the people at https://github.com/unitedstates / https://github.com/unitedstates/congress
 would be interested in.

ping @konklone @JoshData

**Comment by konklone** [comment]
@mlissner's the first name that comes to mind for me :)

**Comment by mlissner** [comment]
Thanks @konklone. Yes, we've been developing opinion scrapers for some years now, and are in the running to get a grant to expand our efforts to even more courts (we currently scrape maybe 30 of them). 

The project we use is a library called juriscraper. We should probably move it to github, but for now it's at: https://bitbucket.org/mlissner/juriscraper

We'd love contributions and have everything from videos documenting the process to a list a jurisdictions we have yet to complete.

Cc: @bwcarver
